service: trestle-services

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage}
  region: us-east-2
  environment:
    DYNAMODB_TABLE: trestle-${self:provider.stage}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "cognito-idp:ListUsers"
       Resource:
         - "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

custom:
  # The following lines are for deploying the service with a custom domain
  # name via the serverless-domain-manager plugin. Please see README.md
  # for more details on custom domain name mapping
  bool:
    true: true
    false: false
  customDomain:
    domainName: ${opt:domain, 'invalid.com'}
    stage: ${self:provider.stage}
    createRoute53Record: true
    enabled: ${self:custom.bool.${opt:enableDomainManager, 'false'}}

functions:
  graphql:
    handler: src/graphql/handler.graphqlHandler
    description: GraphQL API
    events:
      - http:
          path: graphql
          method: get
          cors: true
          authorizer: aws_iam
      - http:
          path: graphql
          method: post
          cors: true
          authorizer: aws_iam

package:
  exclude:
    - node_modules/serverless-offline/**
    - test/**